# serverless.yml

service: sysadap-api-application
custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: sysadap
  region: us-east-1

functions:
  predecir:
      handler: src/handler/TensorflowHandler.predecirTensorflow
      events:
        - http:
            path: /tensorflow/predecir
            method: post
            cors:
              origin: '*'
              headers: ${self:custom.allowedHeaders}